mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls'))
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.main, name='main'),
    path('author/', views.author, name='quote'),
    path('quote/', views.quote, name='quote'),
    path('tag/', views.tag, name='tag'),
    path('detail/<int:note_id>', views.detail, name='detail'),
    path('done/<int:note_id>', views.set_done, name='set_done'),
    path('delete/<int:note_id>', views.delete_note, name='delete'),
]

mysite/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile'),
]

mysite/mysite/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

mysite/polls/models.py
from django.db import models
from django.contrib.auth.models import User

class Author(models.Model):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Quote(models.Model):
    text = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField('Tag')

    def __str__(self):
        return self.text

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# Extending User Model Using a One-To-One Link
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='default_avatar.png', upload_to='profile_images')

    def __str__(self):
        return self.user.username

# resizing images
    def save(self, *args, **kwargs):
        super().save()

mysite/polls/forms.py
from django import forms
from .models import Author, Quote, Tag

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name']

class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['text', 'author', 'tags']

    def __init__(self, *args, **kwargs):
        super(QuoteForm, self).__init__(*args, **kwargs)
        self.fields['author'].queryset = Author.objects.filter(user=self.user)
        self.fields['tags'].queryset = Tag.objects.all()

    def set_user(self, user):
        self.user = user

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name']

mysite/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Profile
class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']


class ProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = Profile
        fields = ['avatar']

mysite/polls/views.py
import datetime
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TagForm, AuthorForm, QuoteForm
from .models import Tag, Author, Quote

def main(request):
    quotes = Quote.objects.filter(user=request.user).all() if request.user.is_authenticated else []
    return render(request, 'polls/index.html', {"quote": quotes})

@login_required
def set_done(request, note_id):
    Quote.objects.filter(pk=note_id, user=request.user).update(done_at=datetime.date.today())
    return redirect(to='polls:main')

@login_required
def delete_note(request, note_id):
    Quote.objects.get(pk=note_id, user=request.user).delete()
    return redirect(to='polls:main')

@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_author = form.save(commit=False)
            new_author.user = request.user
            new_author.save()
            return redirect(to='polls:main')
    else:
        form = AuthorForm()
    return render(request, 'polls/author.html', {'form': form})

@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            new_quote.user = request.user
            new_quote.save()
            form.save_m2m()  # Save many-to-many relationships
            return redirect(to='polls:main')
    else:
        form = QuoteForm()
    return render(request, 'polls/quote.html', {'form': form})

mysite/users/views.py
#from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import RegisterForm, LoginForm, ProfileForm
from .forms import RegisterForm

def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='polls:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='polls:main')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='polls:main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='polls:main')

    return render(request, 'users/login.html', context={"form": LoginForm()})


@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='polls:main')


@login_required
def profile(request):
    return render(request, 'users/profile.html')


@login_required
def profile(request):
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users:profile')

    profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'users/profile.html', {'profile_form': profile_form})

mysite/polls/templates/polls/author.html
{% extends "polls/base.html" %}

{% block content %}

<form method="POST" action="{% url 'polls:add_author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Author name:
            {{ form.name }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

mysite/polls/templates/polls/base.html
<!DOCTYPEhtml>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
           {% if user.is_authenticated %}
        <ul>
            <li><a href="/" role="button">Home</a></li>
            <li><a href="{% url 'polls:note' %}" role="button">Add note</a></li>
            <li><a href="{% url 'polls:tag' %}" role="button">Add Tag</a></li>
        </ul>
        <ul>
            <li>Welcome <b>{{ user.username }}!</b></li>
            <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
            <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <ul>
            <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
            <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
        </ul>
        {% endif %}
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

mysite/polls/templates/polls/detail.html
<!DOCTYPEhtml>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
<!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
<div class="container">

    <form action="{% url 'polls:vote' question.id %}" method="post" class="mb-3">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>{{ question.question_text }}</h1>
            </legend>
            {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            {% for choice in question.choice_set.all %}
            <div class="form-check">
                <input
                        class="form-check-input"
                        type="radio"
                        name="choice"
                        id="choice{{ forloop.counter }}"
                        value="{{ choice.id }}"
                />
                <label for="choice{{ forloop.counter }}" class="form-check-label">{{ choice.choice_text }}</label>
            </div>
            <br/>
            {% endfor %}
        </fieldset>
        <button type="submit" class="btn btn-primary"> Vote</button>
    </form>
    <a href="{% url 'polls:index' %}">Go back to main page</a>
</div>
</body>
</html>

mysite/polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block content %}

    {% for quote in quotes %}
    <ul>
        <li>
            {% if not quote.done %}
            <a href="{% url 'polls:detail' quote.id %}" role="button" class="outline"> {{ quote.name }} </a>
            <a href="{% url 'polls:set_done' quote.id %}" role="button"> Mark Done </a>
            <a href="{% url 'polls:delete' quote.id %}" role="button" class="contrast"> Delete quote </a>
            {% else %}
            <a href="{% url 'polls:detail' quote.id %}" role="button" class="secondary"><s>{{ quote.name }}</s></a>
            {% endif %}
        </li>
    </ul>
    {% endfor %}

{% endblock %}

mysite/polls/templates/polls/note.html
{% extends "polls/base.html" %}

{% block content %}

<form method="POST" action="{% url 'polls:note' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Note name:
            {{ form.name }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label> Note description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div style="padding: 10px">
        <label> Done at:
            {{ form.done_at }}
        </label>
        <span>{{ form.errors.done_at }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

mysite/polls/templates/polls/quote.html
{% extends "polls/base.html" %}

{% block content %}

<form method="POST" action="{% url 'polls:add_quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote text:
            {{ form.text }}
        </label>
        <span>{{ form.errors.text }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author:
            {{ form.author }}
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

mysite/polls/templates/polls/results.html
<!DOCTYPEhtml>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results</title>
<!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <h1>{{ question.question_text }}</h1>

    <ul class="list-unstyled">
        {% for choice in question.choice_set.all %}
        <li class="mb-3">
            {{ choice.choice_text }} &mdash;
            <mark>{{ choice.votes }}</mark>
            vote{{ choice.votes|pluralize }}
        </li>
        {% endfor %}
    </ul>
    <a href="{% url 'polls:detail' question.id %}" class="btn btn-info">Vote again?</a>
</div>

</body>
</html>

mysite/polls/templates/polls/tag.html
{% extends "polls/base.html" %}

{% block content %}

<form method="POST" action="{% url 'polls:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

mysite/users/templates/users/login.html
{% extends "polls/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

mysite/users/templates/users/profile.html
{% extends "polls/base.html" %}

{% block content %}

<div>
    <h1>Profile page: {{user.username}}</h1>
    <img src="{{ user.profile.avatar.url }}" alt="avatar of user"/>
</div>

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
        <div class="col-md-5">
            <div class="form-group">
                <label class="small mb-1">Change Avatar:</label>
                {{ profile_form.avatar }}
                <span>{{ profile_form.errors.avatar }}</span>
            </div>
        </div>
    </div>
    <div class="grid">
        <button type="submit">Save Changes</button>
        <button type="reset" class="secondary">Reset</button>
    </div>

</form>

{% endblock content %}

mysite/users/templates/users/signup.html
{% extends "polls/base.html" %}

{% block content %}

<div>
    <h2>Sign Up</h2>
</div>

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}